version: '3'
services:
  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: voting
    ports:
      - "3306:3306"
    volumes:
      - dataVolume:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - mysql
  backend:
      container_name: nestjs_voting_dev
      image: nestjs-api-dev:1.0.0
      working_dir: /app
      build:
        context: ./server
        target: development
        dockerfile: ./dockerfile
      command: npm run start:dev
      links:
        - mysql
      ports:
        - 3000:3000
      restart: unless-stopped
      depends_on:
        - mysql
  frontend:
    container_name: angular_voting_web_app
    image: angular-simple-votiong-app:1.0.0
    working_dir: /app
    build:
      context: ./client
      dockerfile: ./dockerfile
    ports:
        - 4200:80
    links:
      - backend
    restart: unless-stopped
    depends_on:
      - backend
volumes:
  dataVolume: